### ISSUE TITLE
Move Evaluation to Server

### ISSUE THREAD

**Issue by TalalBazerbachi** [rdsaliba/notorious-eng#276]
Description:
Move the logic of evaluating an RUL model to the Server package so that the UI won't freeze when a user evaluates a model.

Acceptance Criteria:
[-] UI should not freeze when a user evaluates a model.
[-] UI should automatically update the RMSE value when a new value is in the database.
[-] Evaluating a model should be done on a separate thread.
[-] once an evaluation is done, the new RMSE should be stored in the database.
This issue updates [#216]

**Comment by t98b** [comment]
Description:
Move the logic of evaluating an RUL model to the Server package so that the UI won't freeze when a user evaluates a model.

Acceptance Criteria:
[-] UI should not freeze when a user evaluates a model.
[-] UI should automatically update the RMSE value when a new value is in the database.
[-] Evaluating a model should be done on a separate thread.
[-] once an evaluation is done, the new RMSE should be stored in the database
