### ISSUE TITLE
[BUG] Show Asset Type threshold values from Asset Type Info Page

### ISSUE THREAD

**Issue by TalalBazerbachi** [rdsaliba/notorious-eng#286]
Describe the bug
When displaying an asset type information of an asset type that has at least one of its threshold values set to null, it triggers an error in the program.

To Reproduce
1. Open the application
2. Go to the asset type list screen
3. Choose the 4th asset type (id=4). The goal here is to pick any asset type that has a threshold value set to null
4. The application should throw an error

Expected behavior
The program should display the asset type information without triggering an error
![image.png](https://images.zenhubusercontent.com/5e1e31b5ea955f6226a403ec/50bd603f-8b62-4238-a5a5-3a428c91a6e6)

**Comment by JayChouteau** [comment]
@t98b The bug you are describing is different than the screenshot you sent. This error that happens on the screenshot is not when you delete an asset type, the error (1) you are getting is due to the initialization of Data of an asset type on the info page. When the page gets generated, the program tries to populate the threshold text fields parsing (parse double) the values of thresholds stored in the database using our decimal format. However, there is an error due to the fact that some of those values might be null and there is no handling for that.

2) The other bug, which is that the app freezes when you click on the asset type is linked to the fact that the operation is lengthy and probably uses the same thread as the UI thread instead of being run in the server.

In this issue, I will change the description and resolution to fix the error (1) - for the threshold null values. As for error (2), I will create a new issue and take a look at it.

**Comment by JayChouteau** [comment]
Observations/resolution:
1 - The screenshot @t98b  posted was happening when an asset type containing a threshold value that was null. In our code, when that happened, we would set the value to "-" instead. However, when we would try to parse double on that value, it would send us an error.
2 - The value "-" would not show on the text field even if the parse double was removed in the set text method and we only used set text to the string value. That is because of :
thresholdCaution.setTextFormatter(new TextFormatter<>(c -> UIUtilities.checkFormat(TextConstants.ThresholdValueFormat, c)));
The checkFormat() used in this setTextFormatter would use the ThresholdValueFormat which is a Decimal format. However, since "-" couldn't be used with a decimal format, the value return by checkFormat() would be null. This means that no value would be displayed in the textfield.
3 - Given the previous observations, I decided to remove the setting of the value "-" instead of null and add some alternative solution
- When a threshold doesn't have a value, a prompt text is now displayed
- Some null value handling was performed on the textfields

**Comment by JayChouteau** [comment]
Here are some screenshots to show resolution:
1) Delete on asset type correctly deletes the asset type and all related assets (example with asset type ID = 4)
![BUG_deleteTypeFixed_1](https://user-images.githubusercontent.com/47158909/111917965-112fcd80-8a59-11eb-8e3e-57f42ed342f2.PNG)
![BUG_deleteTypeFixed_AssetsDeleted](https://user-images.githubusercontent.com/47158909/111917967-11c86400-8a59-11eb-9603-908a13fead68.PNG)

2) The asset type can show null values for thresholds now
![BUG_ShowTypeFixed_1](https://user-images.githubusercontent.com/47158909/111917980-24db3400-8a59-11eb-9b9c-950dc0706c39.PNG)
