### ISSUE TITLE
Data Preprocessing (F2)

### ISSUE THREAD

**Issue by rdsaliba** [rdsaliba/notorious-eng#95]
F2 - The system shall pre-process and “clean” the raw data

As a user, I want to preprocess the data so that I can calculate the RUL.

Acceptance Criteria:

- [x] Load the system raw data from file and insert loaded data into database
- [x] Reduce the data: the number of data inserted in the database is smaller than the number of initial data

**Comment by jfstamand** [comment]
Your acceptance criterias seems ambiguous to me. 
The accceptance criteria should define the boundaries of a user story, and are used to confirm when a story is completed and working as intended. 

Example:
Instead of 
Create the data (not really testable and you are not really creating the data)
I recommend the following criteria
Load the system raw data from file and insert loaded data into database

**Comment by rdsaliba** [comment]
Hi @jfstamand,
There was a spelling mistake. This should have been "clean the data" and not create. I have fixed it. 

> I recommend the following criteria
> Load the system raw data from file and insert loaded data into database

This is part of F1 and was demonstrated in the demo as well.

This user story is however in relation with the preprocessing requirement of the project. During the demo we have demonstrated that we implemented this ability in the system and submitted a document outlining our methodology for you to review (section 4.8). This include the 3 mentioned acceptance criteria (clean, reduce, transform). If this is this is still ambiguous for you, please let us know what would be required to ameliorate our system or if it satisfies the expectations in order to get your sign off on this requirement.

**Comment by jfstamand** [comment]
Acceptance criterias approved
